language: java

jdk:
 - openjdk8

script: mvn clean install

notifications:
    email:  
        recipients:  
        - jaafar.kaoussarani@polymtl.ca 
        - souleiman.ayoub@polymtl.ca
        on_success: always  
        on_failure: always